# POST http://localhost:8080/ingredient HTTP/1.1
# content-type: application/json

# {
#     "name": "sample1",
#     "unitPrice": 1.0,
#     "quantity": 1.0,
#     "purchaseDate": "2019-01-01",
#     "expiryDate": "2022-10-10"
# }

# GET http://localhost:8080/ingredient HTTP/1.1
# content-type: application/json

GET http://localhost:8080/ingredient/expire HTTP/1.1
content-type: application/json

# POST http://localhost:8080/email HTTP/1.1
# content-type: application/json



